export const GET_CURRENT_LOCATION_REQUEST = "GET_CURRENT_LOCATION_REQUEST";
export const GET_CURRENT_LOCATION_SUCCESS = "GET_CURRENT_LOCATION_SUCCESS";
export const GET_CURRENT_LOCATION_FAILURE = "GET_CURRENT_LOCATION_FAILURE";
